### ISSUE TITLE
Beispiele Lesen - ToDo für jeden! ;-)

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#1]
http://www.instructables.com/id/The-Drone-Pi/

http://www.instructables.com/id/Autonomous-Cardboard-Rasberry-Pi-Controlled-Quad/

https://www.amazon.de/Air-Hogs-6037213-Hyper-Stunt-Drone/dp/B01N11JWTK

Unser Modell soll eine Mischung aus dem Spielzeug von Amazon und den Qudrocoptern werden. (Mit 4 Räder statt 2)

**Comment by gchrizZz** [comment]
http://www.rc-network.de/magazin/artikel_02/art_02-0037/Standschub.pdf 

Hilfreich zur Berechnung und Argumentation fliegt auf dem Mars.

**Comment by MaxMoebes** [comment]
Erledigt.
