### ISSUE TITLE
Falls wir Zeit haben :D

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#19]
Dann könnten wir ja optional die Drohne so auslegen, das sie mit brille gesteuert werden kann. :D 

Vgl.: 
https://www.youtube.com/watch?v=qkURF3jYRHo
Auch 3D kann stabil sein:
https://www.youtube.com/watch?v=vjvlB7RjnYI
https://www.youtube.com/watch?v=K6wfctAFrvw

**Comment by MaxMoebes** [comment]
Zeit für das Projekt zu knapp, wird nicht weiter verfolgt.
