### ISSUE TITLE
Radaufhängung und Achsen konstruieren

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#2]
Radaufhängung für die vorhandenen Räder konstruieren (wir müssen sparen):
3D Druckteil welches wir evtl. an das Chassis schrauben.
Achse warscheinlich aus Alu.

Nachfolgendes nicht mehr gültig!!!:
_https://www.amazon.de/Air-Hogs-6037213-Hyper-Stunt-Drone/dp/B01N11JWTK

Zusätzlich zur Konstruktion Fertigungsmöglichkeiten neben 3D-Druck erarbeiten.

Auch 3D kann stabil sein:
https://www.youtube.com/watch?v=vjvlB7RjnYI
https://www.youtube.com/watch?v=K6wfctAFrvw_

**Comment by MaxMoebes** [comment]
Konstruktion / CAD-Modell mit Inventor erstellt.
