### ISSUE TITLE
Gesamt-Elektronik konzeptionieren

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#20]
Elektronik ist aufwendiger als gedacht...
Und wir brauceh viele Bauteile:

https://www.amazon.de/LHI-MT2204%E2%85%A1-Brushless-Quadcopter-Multicopter/dp/B01E3OT7NE/ref=pd_sim_21_6?_encoding=UTF8&psc=1&refRID=DNGQX9K5C3Z4GB7QD724

https://www.amazon.de/GDD2018-BLHeli-12A-Regler-Quadcopter-Acromodelle/dp/B01D01HVI4/ref=sr_1_6?s=toys&ie=UTF8&qid=1516136137&sr=1-6&keywords=esc

https://www.amazon.de/3-Achsen-Gyroskop-3-Achsen-Accelerometer-Beschleunigungssensor-Neigungssensor-Raspberry/dp/B01F11WXN4/ref=sr_1_1?ie=UTF8&qid=1516132092&sr=8-1&keywords=MPU6050+Motion+Sensor

https://www.amazon.de/GoolRC-Hochleistungs-Luftschrauber-Multirotor-Quadcopter/dp/B00VE7RNQM/ref=sr_1_1?s=toys&ie=UTF8&qid=1516132695&sr=1-1&keywords=6030+propeller

https://www.amazon.de/dp/B01MZHNFDQ/ref=sspa_dk_detail_6?psc=1 + Ladegerät evtl..

**Comment by ChristophJungwirth** [comment]
https://www.ebay.de/itm/Emax-simon-series-ESC-Speed-Controller-Regler-6A-12A-20A-25A-30A-40A-BEC-/232196500670?var=&clk_rvr_id=1419737045115&utm_medium=cpc&utm_source=twenga&utm_campaign=twenga&utm_param=eyJlcyI6MCwicyI6NTMzODY0NywiY2kiOiIwNDNkNzA1OThlMDllOGRiYWRiNjJmZDlkZjgzNjVkZCIsImkiOiIyMzIxOTY1MDA2NzAiLCJ0cyI6MTUxNjM3NTczNCwidiI6Mywic28iOjE1MDAsImMiOjc0MzEyfQ%3D%3D&rmvSB=true

**Comment by gchrizZz** [comment]
Power distributionboard, welches wir selber bauen können.
https://hobbyking.com/en_us/hobby-king-quadcopter-power-distribution-board.html

**Comment by LudiP** [comment]
https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/

die Pinbelegung fürn Pi

**Comment by MaxMoebes** [comment]
Alle Teile Bestellt und geliefert. Power Distribution Board wurde selbst gefertigt. Siehe Platinenkonstruktion.
