### ISSUE TITLE
Simonk ESC calibrieren und motorsterung programmieren

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#27]

**Comment by gchrizZz** [comment]
Es gibt zwei möglichkeiten: Analog oder PWM beides mit Arduino und 4 ESCs möglich
http://www.instructables.com/id/ESC-Programming-on-Arduino-Hobbyking-ESC/
https://github.com/nickshek/arduino-simonK-esc-calibration
http://www.techmonkeybusiness.com/esc-calibration-using-an-arduino.html

**Comment by MaxMoebes** [comment]
Anbei der Code um 1-4 ESC (+Motoren, je nach Bedarf) anzusteuern. Kalibrierung damit wahrscheinlich nicht möglich.
[Kalibrierung_ESC_hobbyking_1_bis_4_Motoren.ino.zip](https://github.com/gchrizZz/RTW/files/1705424/Kalibrierung_ESC_hobbyking_1_bis_4_Motoren.ino.zip)
