### ISSUE TITLE
Steckverbindung HV Akku und Stromplatine fertigen

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#28]

**Comment by MaxMoebes** [comment]
- Passender Stecker für Akku gekauft (5€, siehe Rechnung)
- Power Distribution Board (selbst gefertigt) hat wegen zu hoher Belastung versagt.
   (Ersatzboard bestellt) 
![rechnung_stecker](https://user-images.githubusercontent.com/35543430/35951068-11a41fe2-0c7a-11e8-9e00-98ea612ce0bc.jpg)
