### ISSUE TITLE
Chassi konstruieren

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#3]
Möglichst einfach zu fertigendes und leichtes Chassi konstruieren.
Elektronik muss jedoch vor Wassser geschützt sein.

Max Maße Gesamtfahrzeug:
Länge < 65 cm
Breite < 48 cm
Höhe < 30cm
<10kg

**Comment by gchrizZz** [comment]
https://www.thingiverse.com/thing:1694036
As simple as possible

**Comment by MaxMoebes** [comment]
Konstruktion / CAD-Modell mit Inventor erstellt.
