### ISSUE TITLE
Steuerungscode programmieren

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#4]
Code für rasberry Pi programmieren.
Programmiersprache egal.

Code muss:
4 Motoren steuern können
Gyroskop auslesen können und dementsprechend steuern
Objekterkennung mit der Kamera
Evtl. Ultraschallsensoren auslesen
Notstop via SSH über WLAN o.ä. einbauen

**Comment by gchrizZz** [comment]
https://github.com/PiStuffing/Quadcopter ... wow...

**Comment by gchrizZz** [comment]
https://github.com/matthew-t-watson/Picopter ..dito...

**Comment by LudiP** [comment]
http://www.electronoobs.com/eng_robotica_tut6.php 
sehr cooler arduino code mit anleitung und erklärung

**Comment by MaxMoebes** [comment]
Programmieren ist doof

**Comment by LudiP** [comment]
https://copterflieger.com/2015/01/26/arduino-multiwii-software/

Erklärung um die Multiwii Software auf den Arduino zu spielen

**Comment by MaxMoebes** [comment]
Hier der Link vom Chris für die i2C Verbindung, sollten wir dann am 09.02.17 schaffen einzurichten
https://oscarliang.com/raspberry-pi-arduino-connected-i2c/

**Comment by LudiP** [comment]
https://github.com/lobodol/drone 
pid dingens

**Comment by MaxMoebes** [comment]
Im Code Zeile 296ff auf die entsprechenden Werte von uns abändern (Achtung: ein ESC nicht identisch kalibriert)
