### ISSUE TITLE
Bestellungen in das Forum in moodle eintragen

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#5]
https://weblearn.fh-kufstein.ac.at/mod/forum/view.php?id=12233

Motoren
Akku
Rotorblätter
Welle (Alu) + Schraube + Beilagscheibe evtl. nicht nötig sofern Teller gefräst wird aber viel Materialverbrauch
Schrauben Muttern und Beilagscheiben
Mosgummi
Plastiktüte/Folie
Panzertape!!!
Kabelbinder

**Comment by gchrizZz** [comment]
Nicht mehr nötig

**Comment by MaxMoebes** [comment]
Bestellungen sind bereits erfolgt.
