### ISSUE TITLE
Platinenlayout konstruieren

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/RTW#7]
Konstruktion mit Eagle

**Comment by MaxMoebes** [comment]
Platine ist fertig und getestet, funktioniert

**Comment by MaxMoebes** [comment]
[Mohne Platine.zip](https://github.com/gchrizZz/RTW/files/1691622/Mohne.Platine.zip)

**Comment by MaxMoebes** [comment]
![platine_rover_negativ](https://user-images.githubusercontent.com/35543430/35766276-81effb5c-08d5-11e8-98c2-f165e9f97ad8.png)
